### ISSUE TITLE
这个包还维部维护的？

### ISSUE THREAD

**Issue by callmesoul** [Authing/wxapp-graphql#2]
这个包还维部维护的？
没人回答，也不更新了？

不维护的话我自己fork一个维护，维护的话我可以 pull request

**Comment by callmesoul** [comment]
可以啊

**Comment by zuohuadong** [comment]
@callmesoul  QQ、1256985886

**Comment by leinue** [comment]
维护的

**Comment by leinue** [comment]
稍晚一些兼容 NPM

**Comment by NidMo** [comment]
包还是维护是吗？ 能结合Apollo 相关的包一起用吗

**Comment by leinue** [comment]
> 包还是维护是吗？ 能结合Apollo 相关的包一起用吗

可以的，和 apollo 的接口是一样的

**Comment by NidMo** [comment]
> > 包还是维护是吗？ 能结合Apollo 相关的包一起用吗
> 
> 可以的，和 apollo 的接口是一样的

你这个包等于是apollo client？

**Comment by leinue** [comment]
> > > 包还是维护是吗？ 能结合Apollo 相关的包一起用吗
> > 
> > 
> > 可以的，和 apollo 的接口是一样的
> 
> 你这个包等于是apollo client？

没有 apollo-client 那么完善，比较简单的接口

**Comment by NidMo** [comment]
> > > > 包还是维护是吗？ 能结合Apollo 相关的包一起用吗
> > > 
> > > 
> > > 可以的，和 apollo 的接口是一样的
> > 
> > 
> > 你这个包等于是apollo client？
> 
> 没有 apollo-client 那么完善，比较简单的接口
https://juejin.im/post/5a728da26fb9a01cb74eb328
我看了这篇文章，想试试用apollo-link-state做数据托管，然后在小程序引入了apollo全家桶后，构建npm，项目就报一堆错，在我绝望的时候看到你的包，我不知道能不能结合在一起使用

**Comment by callmesoul** [comment]
应该不可以小程序不是浏览器环境啊很多用不了的，要兼容apollo很难

**Comment by NidMo** [comment]
> 应该不可以小程序不是浏览器环境啊很多用不了的，要兼容apollo很难

https://www.jianshu.com/p/648f7917cdfe
我看到这篇文章，他用wepy跑起来Apollo Client了，然后我就试了下原生来引用，也能跑，但是源码要改一大推，跑到某个函数出问题了，我还没改好，理论上应该能跑的

**Comment by callmesoul** [comment]
@NidMo 
你发那篇文章只是用来基础的发起graphl请求跟传送graphql参数，基本就等于本repo。

但是apollo 最强大的在于它的缓存组件apollo-link-state，client只是发请求，fetch用不了就改成小程序的request就好，而复杂的在这里，估计要改很多，因为小程序很多没有例如localStorag小程序自己的缓存api。改的话就要去看懂它的源码，很费时间。我有去apollo提过叫他们开发个小程序版的，但他们回复重心不在这边，不大会出。靠你

**Comment by NidMo** [comment]
> @NidMo
> 你发那篇文章只是用来基础的发起graphl请求跟传送graphql参数，基本就等于本repo。
> 
> 但是apollo 最强大的在于它的缓存组件apollo-link-state，client只是发请求，fetch用不了就改成小程序的request就好，而复杂的在这里，估计要改很多，因为小程序很多没有例如localStorag小程序自己的缓存api。改的话就要去看懂它的源码，很费时间。我有去apollo提过叫他们开发个小程序版的，但他们回复重心不在这边，不大会出。靠你

我也是看重apollo-link-state，感觉未来前端的数据管理完全可以靠它来完成，但小程序的坑太多了，好难结合在一起啊

**Comment by callmesoul** [comment]
@NidMo 我之前用apollo-vue，发现视图是跟缓存数据绑定的，改data数据不会触发视图更新必须更改缓存数据，所以操作的都是缓存数据，而且会自己配对缓存数据，确实很大强。

**Comment by NidMo** [comment]
> @NidMo 我之前用apollo-vue，发现视图是跟缓存数据绑定的，改data数据不会触发视图更新必须更改缓存数据，所以操作的都是缓存数据，而且会自己配对缓存数据，确实很大强。

我现在开发前端，都比较喜欢将数据剥离处理，将数据都放在store里面进行托管，page和component都只是作为渲染数据的容器，他们逻辑都是操作store里面的数据。保证数据源是单一的

**Comment by callmesoul** [comment]
@NidMo 我是主要把全局的数据才放到store里面进行托管，全部都放store工作量会增大

**Comment by NidMo** [comment]
> @NidMo 我是主要把全局的数据才放到store里面进行托管，全部都放store工作量会增大

我也想过这问题，但最后还是将数据剥离出去，就是不知道对性能影响有多大
