### ISSUE TITLE
使用github v4 api，一直报错,参数应该怎么传？

### ISSUE THREAD

**Issue by bupojung** [Authing/wxapp-graphql#7]
使用github v4 api，一直报错，是哪里错了呢？
错误信息
` {"errors":[{"message":"Parse error on \"$\" (VAR_SIGN) at [2, 12]","locations":[{"line":2,"column":12}]}]}`
代码
`  gql.query({
    query: `{
      user($username: String!) {
        user(login: $username) {
          pullRequests(first: 100, states: OPEN) {
            totalCount
            nodes {
              createdAt
              number
              title
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }
      }
    }`,
    variables: {
      username: 'xxx',
    },
  }).then(res => {
    console.log('graph result: ' + JSON.stringify(res));
  }).catch(res => {
    console.log('graph result: ' + JSON.stringify(res));
  });`

**Comment by leinue** [comment]
检查下语法吧
