### ISSUE TITLE
mutation Cannot query field "createBook" on type "Query".

### ISSUE THREAD

**Issue by menzil** [Authing/wxapp-graphql#9]
我的后端用的是strapi，下面这句在graphql页面测试能正常创建图书，但是在微信小程序里提示“ Cannot query field "createBook" on type "Query".”错误。
mutation {
  createBook(
    input: { data: { name: "gulis", price: 24.50, isbn: "121" } }
  ) {
    book {
      name
      price
      isbn
    }
  }
}

**Comment by leinue** [comment]
你这个是 mutation，小程序里使用的时候要用 gql.mutate，不是 gql.query

**Comment by leinue** [comment]
## 发起 mutation 请求

``` javascript
gql.mutate({
  mutation: 'YOUR_GQL',
  variables: 'YOUR_variables'
})
```

**Comment by menzil** [comment]
> ## 发起 mutation 请求
> ```js
> gql.mutate({
>   mutation: 'YOUR_GQL',
>   variables: 'YOUR_variables'
> })
> ```

谢谢回复，我的小程序里的代码： 
```javascript
addBook() {
		gql.mutate({
			mutation: `{createBook(input: {data: {name: "John",price: "43.66",isbn:"klsdfs"}}) {book {name,price,isbn}}}`,
			variables: {

			}
		}).then(res => {
			console.log(res, 'res');

		})
	}
```

**Comment by leinue** [comment]
> > ## 发起 mutation 请求
> > ```js
> > gql.mutate({
> >   mutation: 'YOUR_GQL',
> >   variables: 'YOUR_variables'
> > })
> > ```
> 
> 谢谢回复，我的小程序里的代码：
> 
> ```js
> addBook() {
> 		gql.mutate({
> 			mutation: `{createBook(input: {data: {name: "John",price: "43.66",isbn:"klsdfs"}}) {book {name,price,isbn}}}`,
> 			variables: {
> 
> 			}
> 		}).then(res => {
> 			console.log(res, 'res');
> 
> 		})
> 	}
> ```

mutation 里是不是少了 `mutation` 字样

**Comment by menzil** [comment]
> mutation
是少了个mutation，解决了。谢谢！
